### ISSUE TITLE
File refences with a valid `filename` without upstream CCS can't be downloaded

### ISSUE THREAD

**Issue by nickygerritsen** [icpctools/icpctools#804]
Imagine contest.yaml has this property:
```yaml
banner:
  - href: contests/bapc2022/banner
    filname: this-is-a-random-filename.svg # Note: NOT banner.svg since that will work
    mime: image/svg+xml
    width: 20000
    height: 1604
```

Then this *will* appear in the contest object in the API, but you can't download the file. There are two issues:
* If the `filename` is not an 'expected' name according to the `getLocalPattern` method in `DiskContestSource`, it will never be considered for donwload. The CDS *will* output the item in the API but opening the link gives a 404.
* The `href` will be copied in full and thus might not work for the CDS. Note that for images/videos (with a width/height) specifically some merging happens in `mergeRefs` in `DiskContestSource`, but for other files (like problem statements or packages) this won't happen.

What I think we should do is, if `filename` is set and the file exists on disk in the correct spot (as per the contest package spec), we ALSO load it and 'merge' it with whatever comes from the contest package (or API?) and thus also update the href to be the CDS URL.

Additionally: should we even drop file refs with an href that can never be something the CDS would support? These files can never be downloaded.
