### ISSUE TITLE
Loading accounts.yaml with \% fails

### ISSUE THREAD

**Issue by nickygerritsen** [icpctools/icpctools#810]
If we put an `accounts.yaml` with the following account in the contest folder:

```yaml
- id: 28
  name: Duck-Team\%
  password: purity-spiny-wobble-freely
  team_id: 742649
  type: team
  username: team28
```

This breaks, since this will be output as `"name": "Duck-Team\%"`, which is not valid JSON. It should be `"name": "Duck-Team\\%"`. In YAML this IS valid though. See https://yaml.org/spec/1.2.2/#57-escaped-characters:

> Note that escape sequences are only interpreted in [double-quoted scalars](https://yaml.org/spec/1.2.2/#double-quoted-style). In all other [scalar styles](https://yaml.org/spec/1.2.2/#node-styles), the “\” character has no special meaning and non-[printable](https://yaml.org/spec/1.2.2/#character-set) characters are not available.

and we didn't (double)quote the string.
